[[pages]]
path = "pages/Login.py"
name = "Login"
icon = "ğŸ”"

[[pages]]
name = "Admin Panel"
icon = "âš™ï¸"
is_section = true

[[pages]]
path = "pages/Admin_Panel.py"
name = "Admin Panel"
icon = "ğŸ› ï¸"

[[pages]]
path = "pages/General Configuration.py"
name = "General Config"
icon = "âš™ï¸"

[[pages]]
path = "pages/Evaluation Panel.py"
name = "Evaluation"
icon = "ğŸ“"

[[pages]]
name = "AI Assistants"
icon = "ğŸ¤–"
is_section = true

[[pages]]
path = "pages/Chatbot.py"
name = "Chatbot"
icon = "ğŸ’¬"

[[pages]]
path = "pages/Jurisbot.py"
name = "Jurisbot"
icon = "âš–ï¸"

[[pages]]
path = "pages/NLP Management.py"
name = "NLP Management"
icon = "ğŸ§ "

[[pages]]
name = "Citizen Engagement"
icon = "ğŸ‘¥"
is_section = true

[[pages]]
path = "pages/Citizen_Space.py"
name = "Citizen Space"
icon = "ğŸŒ"

[[pages]]
path = "pages/Contact_Us.py"
name = "Contact Us"
icon = "ğŸ“¬"

[[pages]]
path = "pages/Our Partners.py"
name = "Our Partners"
icon = "ğŸ¤"

[[pages]]
name = "Security & Privacy"
icon = "ğŸ”"
is_section = true

[[pages]]
path = "pages/Cybersecurity_Reports_(DGSSI).py"
name = "Cybersecurity Reports"
icon = "ğŸ›¡ï¸"

[[pages]]
path = "pages/Your Privacy.py"
name = "Your Privacy"
icon = "ğŸ”"

[[pages]]
name = "Public Sector"
icon = "ğŸ›ï¸"
is_section = true

[[pages]]
path = "pages/Public_Markets & Fundraising.py"
name = "Markets & Fundraising"
icon = "ğŸ’¼"

[[pages]]
path = "pages/Scaling Up & Deploy.py"
name = "Scaling & Deploy"
icon = "ğŸš€"

[[pages]]
name = "Help & Support"
icon = "â“"
is_section = true

[[pages]]
path = "pages/Help.py"
name = "Help"
icon = "ğŸ†˜"
